version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: Install
          command: 'npm install'
      - run:
          name: Test
          command: 'npm test'
      - store_test_results:
          path: 'reports/coverage/clover.xml'
