version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: Install
          command: 'npm install'
      - run:
          name: Test
          command: 'npm test'
      - store_artifacts:
          path: 'reports/coverage'
          prefix: coverage
      - store_artifacts:
          path: 'junit.xml'
          prefix: tests
      - store_test_results:
          path: 'junit.xml'
